name: Deploy React App via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key with Passphrase
        run: |
          # Save the private key and set proper permissions
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          
          # Start the SSH agent
          eval "$(ssh-agent -s)"
          
          # Add the private key to the agent using the passphrase
          echo "$SSH_PASSPHRASE" | ssh-add private_key <<< "$SSH_PASSPHRASE"
          
          # Verify the key is added
          ssh-add -l

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key root@103.108.140.185 "echo Connected Successfully!"

      - name: Deploy React App (Optional Step)
        run: |
          scp -o StrictHostKeyChecking=no -i private_key -r ./build/* root@103.108.140.185:/var/www/react-app
          ssh -o StrictHostKeyChecking=no -i private_key root@103.108.140.185 "sudo systemctl restart nginx"
          
      - name: Clean Up SSH Agent
        run: |
          ssh-agent -k
